class StatisticsController < ApplicationController
    before_filter :authorize
  def index
    @teams = Team.all
    @red = Team.find_by_name("Red")
    @green = Team.find_by_name("Green")
    @blue = Team.find_by_name("Blue")
    @yellow = Team.find_by_name("Yellow")
    @sg_6m = Stampeder.find_all_by_subgroup("6m")
    @sg_7m = Stampeder.find_all_by_subgroup("7m")
    @sg_8m = Stampeder.find_all_by_subgroup("8m")
    @sg_9m = Stampeder.find_all_by_subgroup("9m")
    @sg_6f = Stampeder.find_all_by_subgroup("6f")
    @sg_7f = Stampeder.find_all_by_subgroup("7f")
    @sg_8f = Stampeder.find_all_by_subgroup("8f")
    @sg_9f = Stampeder.find_all_by_subgroup("9f")
    @red_6m = Stampeder.find_all_by_team_id_and_subgroup(1,"6m")
    @red_7m = Stampeder.find_all_by_team_id_and_subgroup(1,"7m")
    @red_8m = Stampeder.find_all_by_team_id_and_subgroup(1,"8m")
    @red_9m = Stampeder.find_all_by_team_id_and_subgroup(1,"9m")
    @red_6f = Stampeder.find_all_by_team_id_and_subgroup(1,"6f")
    @red_7f = Stampeder.find_all_by_team_id_and_subgroup(1,"7f")
    @red_8f = Stampeder.find_all_by_team_id_and_subgroup(1,"8f")
    @red_9f = Stampeder.find_all_by_team_id_and_subgroup(1,"9f")
    @green_6m = Stampeder.find_all_by_team_id_and_subgroup(2,"6m")
    @green_7m = Stampeder.find_all_by_team_id_and_subgroup(2,"7m")
    @green_8m = Stampeder.find_all_by_team_id_and_subgroup(2,"8m")
    @green_9m = Stampeder.find_all_by_team_id_and_subgroup(2,"9m")
    @green_6f = Stampeder.find_all_by_team_id_and_subgroup(2,"6f")
    @green_7f = Stampeder.find_all_by_team_id_and_subgroup(2,"7f")
    @green_8f = Stampeder.find_all_by_team_id_and_subgroup(2,"8f")
    @green_9f = Stampeder.find_all_by_team_id_and_subgroup(2,"9f")
    @blue_6m = Stampeder.find_all_by_team_id_and_subgroup(3,"6m")
    @blue_7m = Stampeder.find_all_by_team_id_and_subgroup(3,"7m")
    @blue_8m = Stampeder.find_all_by_team_id_and_subgroup(3,"8m")
    @blue_9m = Stampeder.find_all_by_team_id_and_subgroup(3,"9m")
    @blue_6f = Stampeder.find_all_by_team_id_and_subgroup(3,"6f")
    @blue_7f = Stampeder.find_all_by_team_id_and_subgroup(3,"7f")
    @blue_8f = Stampeder.find_all_by_team_id_and_subgroup(3,"8f")
    @blue_9f = Stampeder.find_all_by_team_id_and_subgroup(3,"9f")
    @yellow_6m = Stampeder.find_all_by_team_id_and_subgroup(4,"6m")
    @yellow_7m = Stampeder.find_all_by_team_id_and_subgroup(4,"7m")
    @yellow_8m = Stampeder.find_all_by_team_id_and_subgroup(4,"8m")
    @yellow_9m = Stampeder.find_all_by_team_id_and_subgroup(4,"9m")
    @yellow_6f = Stampeder.find_all_by_team_id_and_subgroup(4,"6f")
    @yellow_7f = Stampeder.find_all_by_team_id_and_subgroup(4,"7f")
    @yellow_8f = Stampeder.find_all_by_team_id_and_subgroup(4,"8f")
    @yellow_9f = Stampeder.find_all_by_team_id_and_subgroup(4,"9f")
    @stampeders = Stampeder.all
  end
end
